import { REPORT } from "./constants.js";
import {
  drawHorizontalLine,
  formatDateTime,
  getLogoPath,
  logoExists,
} from "./helpers.js";

/**
 * Draw report header
 */
export const drawHeader = (doc, title) => {
  if (logoExists()) {
    doc.image(getLogoPath(), 40, 30, {
      width: 55,
    });
  }

  doc
    .fontSize(20)
    .fillColor(REPORT.PRIMARY_COLOR)
    .text(REPORT.COMPANY_NAME, 110, 40);

  doc.fontSize(16).fillColor("#222222").text(title, 110, 68);

  doc
    .fontSize(10)
    .fillColor("#666666")
    .text(`Generated By : ${REPORT.GENERATED_BY}`, 40, 105);

  doc.text(`Generated On : ${formatDateTime(new Date())}`, 250, 105);

  drawHorizontalLine(doc, 125);
};
