import { REPORT } from "./constants.js";
import { formatDateTime } from "./helpers.js";

export const drawReportHeader = (doc, { title, description, continuation = false }) => {
  const pageWidth = doc.page.width;
  const margin = REPORT.PAGE_MARGIN;

  if (continuation) {
    doc
      .fillColor(REPORT.PRIMARY_COLOR)
      .font("Helvetica-Bold")
      .fontSize(11)
      .text(REPORT.SHORT_NAME, margin, 25, { lineBreak: false });

    doc
      .fillColor(REPORT.TEXT_DARK)
      .font("Helvetica-Bold")
      .fontSize(12)
      .text(`${title} - Continued`, margin + 55, 25, {
        width: pageWidth - margin * 2 - 55,
        lineBreak: false,
      });

    doc
      .moveTo(margin, 47)
      .lineTo(pageWidth - margin, 47)
      .strokeColor(REPORT.BORDER_COLOR)
      .lineWidth(0.8)
      .stroke();

    return 62;
  }

  doc.save();
  doc.rect(0, 0, pageWidth, 82).fill(REPORT.PRIMARY_COLOR);

  doc
    .fillColor("#FFFFFF")
    .font("Helvetica-Bold")
    .fontSize(10)
    .text(REPORT.COMPANY_NAME.toUpperCase(), margin, 21, {
      width: pageWidth - margin * 2,
      characterSpacing: 0.5,
      lineBreak: false,
    });

  doc
    .font("Helvetica-Bold")
    .fontSize(21)
    .text(title, margin, 40, {
      width: pageWidth - margin * 2,
      lineBreak: false,
    });
  doc.restore();

  const metaY = 97;
  doc
    .fillColor(REPORT.TEXT_MUTED)
    .font("Helvetica")
    .fontSize(8.5)
    .text("GENERATED BY", margin, metaY, { lineBreak: false });
  doc
    .fillColor(REPORT.TEXT_DARK)
    .font("Helvetica-Bold")
    .fontSize(9.5)
    .text(REPORT.GENERATED_BY, margin, metaY + 12, { lineBreak: false });

  doc
    .fillColor(REPORT.TEXT_MUTED)
    .font("Helvetica")
    .fontSize(8.5)
    .text("GENERATED ON", margin + 125, metaY, { lineBreak: false });
  doc
    .fillColor(REPORT.TEXT_DARK)
    .font("Helvetica-Bold")
    .fontSize(9.5)
    .text(formatDateTime(new Date()), margin + 125, metaY + 12, {
      width: 190,
      lineBreak: false,
    });

  if (description) {
    doc
      .fillColor(REPORT.TEXT_MUTED)
      .font("Helvetica")
      .fontSize(9)
      .text(description, pageWidth - margin - 350, metaY, {
        width: 350,
        align: "right",
        lineBreak: false,
      });
  }

  doc
    .moveTo(margin, 126)
    .lineTo(pageWidth - margin, 126)
    .strokeColor(REPORT.BORDER_COLOR)
    .lineWidth(0.8)
    .stroke();

  return 139;
};
